### PR TITLE
Small highlighting improvements

### PR DESCRIPTION
**Pull request by eric-wieser**
This fixes a bug that caused every character to be highlighted separately in identifier names.

The rest of the changes aren't a particularly principled, but were what I used in my FMM2021 presentation.

In particular, this is written with the assumption that the user add a `.hljs-sorry` to their stylesheet in order to get red sorrys.

---
- [x] depends on: #10

### CODE REVIEW

**Comment by bryangingechen** [comment]
Would it be better to have `sorry` highlighted automatically by `hljs` rather than making users add their own custom CSS? `pygments` highlights them as some kind of error: https://github.com/pygments/pygments/blob/master/pygments/lexers/theorem.py#L442

**Comment by eric-wieser** [comment]
Hljs didn't seem to have a suitable builtin class name for our use as I recall, unlike pygments which has heirarchical scopes.

**Comment by bryangingechen** [comment]
I see, in that case would you mind adding a line to the README about `sorry` then?

**Review by bryangingechen — APPROVED** [review]
LGTM. Feel free to merge yourself after fixing the merge conflict. I'll look into making a release later tonight or this weekend.

**Pull request merged**
